//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=hestia;Initial Catalog=PLASMARSA;Persist Security Info=True;User ID=o" +
            "fimatica;Password=ofimatica")]
        public string PLASMARSAConnectionString {
            get {
                return ((string)(this["PLASMARSAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=hestia;Initial Catalog=PLASMARSA;Integrated Security=True;Connect Tim" +
            "eout=30;Encrypt=False;TrustServerCertificate=False")]
        public string PLASMARSAConnectionString1 {
            get {
                return ((string)(this["PLASMARSAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=hestia;Initial Catalog=PLASMARSA;Persist Security Info=True;User ID=o" +
            "fimatica;Password=ofimatica;MultipleActiveResultSets=True;Application Name=Entit" +
            "yFramework")]
        public string PLASMARSAConnectionString2 {
            get {
                return ((string)(this["PLASMARSAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=hestia;Initial Catalog=PLASMARSA;Integrated Security=True")]
        public string PLASMARSAConnectionString3 {
            get {
                return ((string)(this["PLASMARSAConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Hestia;Initial Catalog=PLASMARSA;Persist Security Info=True;User ID=o" +
            "fimatica;Password=ofimatica")]
        public string PLASMARSAConnectionString4 {
            get {
                return ((string)(this["PLASMARSAConnectionString4"]));
            }
        }
    }
}
